language: ruby
cache: bundler

gemfile:
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile

before_script:
  - bundle exec rake setup

script:
  - bundle exec rake

rvm:
  - 2.5.8
  - 2.6.6
